/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  genesis_time: number;
  genesis_validators_root: string;
  seconds_per_slot: number;
  slots_per_period: number;
  sync_committee_period: number;
  sync_committee_poseidon: string;
}
export type ExecuteMsg = {
  step: {
    execution_state_root: string;
    finalized_header_root: string;
    finalized_slot: number;
    participation: number;
    proof_a: [string, string];
    proof_b: [[string, string], [string, string]];
    proof_c: [string, string];
  };
} | {
  rotate: {
    execution_state_root: string;
    finalized_header_root: string;
    finalized_slot: number;
    participation: number;
    rotate_proof_a: [string, string];
    rotate_proof_b: [[string, string], [string, string]];
    rotate_proof_c: [string, string];
    step_proof_a: [string, string];
    step_proof_b: [[string, string], [string, string]];
    step_proof_c: [string, string];
    sync_committee_poseidon: string;
    sync_committee_ssz: string;
  };
} | {
  force: {
    period: number;
  };
};
export type QueryMsg = {
  get_sync_committee_period: {
    slot: Uint256;
  };
} | {
  get_current_slot: {};
};
export type Uint256 = string;
export type MigrateMsg = string;
export interface GetCurrentSlotResponse {
  slot: Uint256;
}
export interface GetSyncCommitteePeriodResponse {
  period: Uint256;
}